# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ambra-os
description: Sistema immutabile con Docker e supporto Windows per Ambra.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - micro
      - git
      - fastfetch
      - docker
      - docker-compose
      - podman
      - wine-core
      - winetricks

  - type: default-flatpaks
    notify: true
    install:
      - org.mozilla.firefox
      - com.usebottles.bottles
      - com.visualstudio.code

  - type: signing
