# Nome della tua creazione
name: Ambra-OS
description: Una distro immutabile con Docker e supporto Windows

# Usiamo Fedora come base (solida e moderna)
base-image: ghcr.io/ublue-os/base-main
image-version: 39

modules:
  - type: rpm-ostree
    install:
      # --- STRUMENTI PER I CONTAINER ---
      - docker
      - docker-compose
      - podman # L'alternativa moderna a Docker
      
      # --- COMPATIBILITÀ WINDOWS ---
      - wine-core # Per avviare i file .exe
      - winetricks # Per installare librerie Windows mancanti
      
      # --- UTILITY DI SISTEMA ---
      - git
      - fastfetch # Per mostrare il logo della tua distro nel terminale

  - type: default-flatpaks
    notify: true
    install:
      # Bottles è la migliore interfaccia per gestire app Windows su Linux
      - com.usebottles.bottles
      - com.visualstudio.code # Editor per programmare
