# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ambra-os
description: Sistema con Docker, Supporto Windows, Chrome e Office.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - micro
      - git
      - fastfetch
      - docker
      - docker-compose
      - podman
      - wine-core
      - winetricks

  - type: default-flatpaks
    configurations:
      - notify: true
        install:
          - org.mozilla.firefox
          - org.libreoffice.LibreOffice
          - com.usebottles.bottles
          - com.visualstudio.code
